### PR TITLE
Included SDKs in the plugin

### PR DESCRIPTION
**Pull request by peder541**
The Twilio Client SDK files are in the sdk folder and separated by platform.
plugin.xml makes sure these source files get installed in the correct location and linked properly.

### CODE REVIEW

**Comment by peder541** [comment]
Jeff, have you had a change to look at this?

**Comment by jefflinwood** [comment]
Hi, somehow I missed the update you put in! Let me take another look.

**Comment by peder541** [comment]
Twilio released updated SDKs today that fix some important bugs, especially for Android.
I thought it would be good to include them in this pull request.

**Comment by jefflinwood** [comment]
I definitely agree there should be the latest versions of the SDKs in this plugin - and perhaps the plugin versioning should match the SDK versioning - maybe 1.2.2.1, for instance?

**Comment by peder541** [comment]
I think that style of versioning makes a lot of sense. Do you know if the Cordova Plugin Registry would support four digits in the version number like that?

**Comment by jefflinwood** [comment]
That I don't know - I'm also not sure if this would be eligible for the PhoneGap Build, but that would be great as well

**Comment by sb8244** [comment]
Hi, this PR makes it possible to use twilio client phonegap in an ionic build. Ionic builds the xcodeproj for you, and including the libraries there can be a real PITA (haven't figured out how to do it yet).

**Comment by peder541** [comment]
Any chance we can resolve this?

**Comment by northkode** [comment]
Is this going to get merged? What is the status of master? are the memory and destroy issues fixed?

**Pull request closed without merging**
